#!/bin/bash
adb devices
sleep 2
adb push /usr/bin/scrcpy-server-v1.2.jar /data/local/tmp/
adb reverse localabstract:scrcpy tcp:56100
nc -l -p 56100 > /home/pi/Video/streamer &
omxplayer -o hdmi --no-keys --no-osd --refresh  --advanced=0 --loop --timeout 0 --lavfdopts probesize:250000 --video_queue 1 --avdict rtsp_transport:tcp  /home/pi/Video/streamer &
sleep 5
adb shell CLASSPATH=/data/local/tmp/scrcpy-server-v1.2.jar app_process / com.genymobile.scrcpy.Server 0 8000000 false 
exit 0

